### PR TITLE
untracked: Add error if request body is too large for receiving syste…

### PR DESCRIPTION
**Pull request by oliverbock**
…m, so user can understand what the problem is.  Prevented newlines between lines in JSON to save a little space.

### CODE REVIEW

**Review by mwm-displayr — CHANGES_REQUESTED** [review]
Just some warnings in the package check due to undocumented arguments. can you document and roxygenize pls? https://app.circleci.com/pipelines/github/Displayr/flipAPI/133/workflows/c8f2aa32-45e4-4cbd-87d3-b747428869ce/jobs/162

**Comment by oliverbock** [comment]
Thanks, @mwm-displayr , I've fixed those.

**Review by chrisfacer — APPROVED** [review]

**Comment by chrisfacer** [comment]
Looks good but there is a failing unit test @oliverbock

**Comment by jankurianski** [comment]
FYI I also fixed up the docs in my PR here to get it through https://github.com/Displayr/flipAPI/pull/36

I added a `skip()` to the failing unit test, so you'll need to rebase against `master` and remove it (presuming my PR is merged in first).

**Pull request merged**
